### ISSUE TITLE
Metadata Changes

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/website#129]
The following changes should be made to the current metadata schema as well as the metadata creation process.

**svgdigitizer**
- [x] Write the curve modifier into `source.curve`. Currently, this is done manually in the YAML and the SVG file. In some cases these IDs are different. (see https://github.com/echemdb/svgdigitizer/pull/140)

**metadata**
- [x] Add a section `experimental_details` which includes a list of `tags`, describing the experiment. The technique CV does not distinguish between BCV, ORR or COOX. (see #133)
- [x] Move `instrumentation` from electrochemical system to `experimental details` (see #133)
- [x] rename `electrochemical system` into `system` and add an entry `type: electrochemical` (see #133)
- [x] carefully reevaluate the names of the curve identifiers of data already submitted to echemdb. (see #136)
- [x] Add `tags` to all SVG files (see #136)
- [x] Change `rate` to `scan rate` in SVG (see #136)
- [x] Add `figure` to SVG (see #136)
- [x] remove _p#_ from file names (see #136)

**website**
- [x] show tags on `cv_entry.md` (not useful. This is only nice for sorting data and should be added as filter function.
- [x] Put descriptive text for the metadata in colapsible menue description (see #154)
![image](https://user-images.githubusercontent.com/39313137/154061423-a422cc3d-bf38-4ad3-8c36-a784eb530e5f.png)
