### ISSUE TITLE
Build cv_entry template for an individual data package

### ISSUE THREAD

**Issue by saraedum** [echemdb/website#31]
# Tasks:

* [x] Create the heading `Pt(111)` from metadata. (see #37)
* [x] Create the small heading subtitle from metadata.
    * [x]  see below electrolyte  (see #81)
* [x] Create introductory text from metadata.
    * [x] Create entries that can be extracted directly from metadata file (see #37)
    * [x] Create electrolyte text
       * [x] Loop over components and print component name + concentration_unit (see #81)
    * [x] Create entry for scan rate (see #81)
    * [x] Create literature link (see #69 and see #77)
    * [x] include the Figure identifier in the description (raised in #52) (implemented in #88 as label of the curve n the plot) 
* [x] Create literature reference from .bib files. (see #69 and see #77)
* [x] Properly format plots.
   * [x] render plots with original figure units (see #88)
   * [x] Add Reference scale on x-Axis (see #88)
* [x] Add the comment from metadata below the plot 
    * [x] once https://github.com/echemdb/svgdigitizer/pull/93 is done
    * [x] Also indicate if the data is digitized or if it is raw data (see #37)
* [x] Add collapsible bibliography in bibtex style. (see #94)
* [x] Create collapsible figure description section inlcuding a short text for the meaning of this data (see #89)
* [ ] Style "Further Information" section. #113 
* [x] Make metadata from .yaml file available, e.g., by showing the metadata formatted as YAML with syntax highlighting. (see #40)
* [x] Remove duplicate sections about electrolyte, reference electrode and scan rate. (see #37)

**Comment by saraedum** [comment]
What should that button do exactly? That might be a lot of work to implement actually. But maybe just a link that points to instructions how to improve the data if you are the author...would be good?

**Comment by DunklesArchipel** [comment]
Would it be useful to have a report button, if there are mistakes for example in the metadata file? I don't think that everyone knows how to create an issue or a pull request.

**Comment by DunklesArchipel** [comment]
Note: Package to transform strings to markdown:

https://pypi.org/project/markdown-strings/
